import './globals.css';
import { Open_Sans } from 'next/font/google';
import Navbar from '@/components/Navbar';

const openSans = Open_Sans({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={openSans.className}>
      <body className="w-full overflow-auto">
        <header className="sticky h-[64px] top-0 z-20 bg-white border-b opacity-90">
          <Navbar />
        </header>
        <main className="flex flex-col w-full h-[calc(100%-64px)] max-w-screen-2xl mx-auto">
          {children}
        </main>
      </body>
    </html>
  );
}
